import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

import Header from '../components/Header'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className="w-screen h-screen">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Component {...pageProps} />
    </div>
  )
}

export default MyApp
